# Generated by Django 2.0.3 on 2018-10-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_passengers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengers',
            name='flight',
            field=models.ManyToManyField(blank=True, related_name='flights', to='flights.Flight'),
        ),
    ]
